package ddb.web.util;

import ddb.util.ByteUtils;
import java.awt.Color;
import java.util.HashMap;
import java.util.Map;

public class HTMLColor extends Color {
   public static final String classVersion = "5.5";
   public static final long serialVersionUID = 3729060382348670040L;
   protected static final Map<String, Color> nameToColorMap = new HashMap();
   protected static final Map<Color, String> colorToStringMap = new HashMap();
   public static final HTMLColor ALICEBLUE = new HTMLColor("aliceblue", "#f0f8ff");
   public static final HTMLColor ANTIQUEWHITE = new HTMLColor("antiquewhite", "#faebd7");
   public static final HTMLColor ANTIQUEWHITE1 = new HTMLColor("antiquewhite1", "#ffefdb");
   public static final HTMLColor ANTIQUEWHITE2 = new HTMLColor("antiquewhite2", "#eedfcc");
   public static final HTMLColor ANTIQUEWHITE3 = new HTMLColor("antiquewhite3", "#cdc0b0");
   public static final HTMLColor ANTIQUEWHITE4 = new HTMLColor("antiquewhite4", "#8b8378");
   public static final HTMLColor AQUA = new HTMLColor("aqua", "#00ffff");
   public static final HTMLColor AQUAMARINE = new HTMLColor("aquamarine", "#7fffd4");
   public static final HTMLColor AQUAMARINE1 = new HTMLColor("aquamarine1", "#7fffd4");
   public static final HTMLColor AQUAMARINE2 = new HTMLColor("aquamarine2", "#76eec6");
   public static final HTMLColor AQUAMARINE3 = new HTMLColor("aquamarine3", "#66cdaa");
   public static final HTMLColor AQUAMARINE4 = new HTMLColor("aquamarine4", "#458b74");
   public static final HTMLColor AZURE = new HTMLColor("azure", "#f0ffff");
   public static final HTMLColor AZURE1 = new HTMLColor("azure1", "#f0ffff");
   public static final HTMLColor AZURE2 = new HTMLColor("azure2", "#e0eeee");
   public static final HTMLColor AZURE3 = new HTMLColor("azure3", "#c1cdcd");
   public static final HTMLColor AZURE4 = new HTMLColor("azure4", "#838b8b");
   public static final HTMLColor BEIGE = new HTMLColor("beige", "#f5f5dc");
   public static final HTMLColor BISQUE = new HTMLColor("bisque", "#fffaf0");
   public static final HTMLColor BISQUE1 = new HTMLColor("bisque1", "#ffe4c4");
   public static final HTMLColor BISQUE2 = new HTMLColor("bisque2", "#eed5b7");
   public static final HTMLColor BISQUE3 = new HTMLColor("bisque3", "#cdb79e");
   public static final HTMLColor BISQUE4 = new HTMLColor("bisque4", "#8b7d6b");
   public static final HTMLColor BLACK = new HTMLColor("black", "#000000");
   public static final HTMLColor BLANCHEDALMOND = new HTMLColor("blanchedalmond", "#ffebcd");
   public static final HTMLColor BLUE = new HTMLColor("blue", "#0000ff");
   public static final HTMLColor BLUE1 = new HTMLColor("blue1", "#0000ff");
   public static final HTMLColor BLUE2 = new HTMLColor("blue2", "#0000ee");
   public static final HTMLColor BLUE3 = new HTMLColor("blue3", "#0000cd");
   public static final HTMLColor BLUE4 = new HTMLColor("blue4", "#00008b");
   public static final HTMLColor BLUEVIOLET = new HTMLColor("blueviolet", "#8a2be2");
   public static final HTMLColor BROWN = new HTMLColor("brown", "#a52a2a");
   public static final HTMLColor BROWN1 = new HTMLColor("brown1", "#ff4040");
   public static final HTMLColor BROWN2 = new HTMLColor("brown2", "#ee3b3b");
   public static final HTMLColor BROWN3 = new HTMLColor("brown3", "#cd3333");
   public static final HTMLColor BROWN4 = new HTMLColor("brown4", "#8b2323");
   public static final HTMLColor BURLYWOOD = new HTMLColor("burlywood", "#deb887");
   public static final HTMLColor BURLYWOOD1 = new HTMLColor("burlywood1", "#ffd39b");
   public static final HTMLColor BURLYWOOD2 = new HTMLColor("burlywood2", "#eec591");
   public static final HTMLColor BURLYWOOD3 = new HTMLColor("burlywood3", "#cdaa7d");
   public static final HTMLColor BURLYWOOD4 = new HTMLColor("burlywood4", "#8b7355");
   public static final HTMLColor CADETBLUE = new HTMLColor("cadetblue", "#5f9ea0");
   public static final HTMLColor CADETBLUE1 = new HTMLColor("cadetblue1", "#98f5ff");
   public static final HTMLColor CADETBLUE2 = new HTMLColor("cadetblue2", "#8ee5ee");
   public static final HTMLColor CADETBLUE3 = new HTMLColor("cadetblue3", "#7ac5cd");
   public static final HTMLColor CADETBLUE4 = new HTMLColor("cadetblue4", "#53868b");
   public static final HTMLColor CHARTREUSE = new HTMLColor("chartreuse", "#7fff00");
   public static final HTMLColor CHARTREUSE1 = new HTMLColor("chartreuse1", "#7fff00");
   public static final HTMLColor CHARTREUSE2 = new HTMLColor("chartreuse2", "#76ee00");
   public static final HTMLColor CHARTREUSE3 = new HTMLColor("chartreuse3", "#66cd00");
   public static final HTMLColor CHARTREUSE4 = new HTMLColor("chartreuse4", "#458b00");
   public static final HTMLColor CHOCOLATE = new HTMLColor("chocolate", "#d2691e");
   public static final HTMLColor CHOCOLATE1 = new HTMLColor("chocolate1", "#ff7f24");
   public static final HTMLColor CHOCOLATE2 = new HTMLColor("chocolate2", "#ee7621");
   public static final HTMLColor CHOCOLATE3 = new HTMLColor("chocolate3", "#cd661d");
   public static final HTMLColor CHOCOLATE4 = new HTMLColor("chocolate4", "#8b4513");
   public static final HTMLColor CORAL = new HTMLColor("coral", "#ff7f50");
   public static final HTMLColor CORAL1 = new HTMLColor("coral1", "#ff7256");
   public static final HTMLColor CORAL2 = new HTMLColor("coral2", "#ee6a50");
   public static final HTMLColor CORAL3 = new HTMLColor("coral3", "#cd5b45");
   public static final HTMLColor CORAL4 = new HTMLColor("coral4", "#8b3e2f");
   public static final HTMLColor CORNFLOWERBLUE = new HTMLColor("cornflowerblue", "#6495ed");
   public static final HTMLColor CORNSILK = new HTMLColor("cornsilk", "#fff8dc");
   public static final HTMLColor CORNSILK1 = new HTMLColor("cornsilk1", "#fff8dc");
   public static final HTMLColor CORNSILK2 = new HTMLColor("cornsilk2", "#eee8cd");
   public static final HTMLColor CORNSILK3 = new HTMLColor("cornsilk3", "#cdc8b1");
   public static final HTMLColor CORNSILK4 = new HTMLColor("cornsilk4", "#8b8878");
   public static final HTMLColor CYAN = new HTMLColor("cyan", "#00ffff");
   public static final HTMLColor CYAN1 = new HTMLColor("cyan1", "#00ffff");
   public static final HTMLColor CYAN2 = new HTMLColor("cyan2", "#00eeee");
   public static final HTMLColor CYAN3 = new HTMLColor("cyan3", "#00cdcd");
   public static final HTMLColor CYAN4 = new HTMLColor("cyan4", "#008b8b");
   public static final HTMLColor DARKBLUE = new HTMLColor("darkblue", "#00008b");
   public static final HTMLColor DARKCYAN = new HTMLColor("darkcyan", "#008b8b");
   public static final HTMLColor DARKGOLDENROD = new HTMLColor("darkgoldenrod", "#b8860b");
   public static final HTMLColor DARKGOLDENROD1 = new HTMLColor("darkgoldenrod1", "#ffb90f");
   public static final HTMLColor DARKGOLDENROD2 = new HTMLColor("darkgoldenrod2", "#eead0e");
   public static final HTMLColor DARKGOLDENROD3 = new HTMLColor("darkgoldenrod3", "#cd950c");
   public static final HTMLColor DARKGOLDENROD4 = new HTMLColor("darkgoldenrod4", "#8b658b");
   public static final HTMLColor DARKGRAY = new HTMLColor("darkgray", "#a9a9a9");
   public static final HTMLColor DARKGREEN = new HTMLColor("darkgreen", "#006400");
   public static final HTMLColor DARKGREY = new HTMLColor("darkgrey", "#a9a9a9");
   public static final HTMLColor DARKKHAKI = new HTMLColor("darkkhaki", "#bdb76b");
   public static final HTMLColor DARKMAGENTA = new HTMLColor("darkmagenta", "#8b008b");
   public static final HTMLColor DARKOLIVEGREEN = new HTMLColor("darkolivegreen", "#556b2f");
   public static final HTMLColor DARKOLIVEGREEN1 = new HTMLColor("darkolivegreen1", "#caff70");
   public static final HTMLColor DARKOLIVEGREEN2 = new HTMLColor("darkolivegreen2", "#bcee68");
   public static final HTMLColor DARKOLIVEGREEN3 = new HTMLColor("darkolivegreen3", "#a2cd5a");
   public static final HTMLColor DARKOLIVEGREEN4 = new HTMLColor("darkolivegreen4", "#6e8b3d");
   public static final HTMLColor DARKORANGE = new HTMLColor("darkorange", "#ff8c00");
   public static final HTMLColor DARKORANGE1 = new HTMLColor("darkorange1", "#ff7f00");
   public static final HTMLColor DARKORANGE2 = new HTMLColor("darkorange2", "#ee7600");
   public static final HTMLColor DARKORANGE3 = new HTMLColor("darkorange3", "#cd6600");
   public static final HTMLColor DARKORANGE4 = new HTMLColor("darkorange4", "#8b4500");
   public static final HTMLColor DARKORCHID = new HTMLColor("darkorchid", "#9932cc");
   public static final HTMLColor DARKORCHID1 = new HTMLColor("darkorchid1", "#bf3eff");
   public static final HTMLColor DARKORCHID2 = new HTMLColor("darkorchid2", "#b23aee");
   public static final HTMLColor DARKORCHID3 = new HTMLColor("darkorchid3", "#9a32cd");
   public static final HTMLColor DARKORCHID4 = new HTMLColor("darkorchid4", "#68228b");
   public static final HTMLColor DARKRED = new HTMLColor("darkred", "#8b0000");
   public static final HTMLColor DARKSALMON = new HTMLColor("darksalmon", "#e9967a");
   public static final HTMLColor DARKSEAGREEN = new HTMLColor("darkseagreen", "#8fbc8f");
   public static final HTMLColor DARKSEAGREEN1 = new HTMLColor("darkseagreen1", "#c1ffc1");
   public static final HTMLColor DARKSEAGREEN2 = new HTMLColor("darkseagreen2", "#b4eeb4");
   public static final HTMLColor DARKSEAGREEN3 = new HTMLColor("darkseagreen3", "#9bcd9b");
   public static final HTMLColor DARKSEAGREEN4 = new HTMLColor("darkseagreen4", "#698b69");
   public static final HTMLColor DARKSLATEBLUE = new HTMLColor("darkslateblue", "#483d8b");
   public static final HTMLColor DARKSLATEGRAY = new HTMLColor("darkslategray", "#2f4f4f");
   public static final HTMLColor DARKSLATEGRAY1 = new HTMLColor("darkslategray1", "#97ffff");
   public static final HTMLColor DARKSLATEGRAY2 = new HTMLColor("darkslategray2", "#8deeee");
   public static final HTMLColor DARKSLATEGRAY3 = new HTMLColor("darkslategray3", "#79cdcd");
   public static final HTMLColor DARKSLATEGRAY4 = new HTMLColor("darkslategray4", "#528b8b");
   public static final HTMLColor DARKTURQUOISE = new HTMLColor("darkturquoise", "#00ced1");
   public static final HTMLColor DARKVIOLET = new HTMLColor("darkviolet", "#9400d3");
   public static final HTMLColor DEEPPINK = new HTMLColor("deeppink", "#ff1493");
   public static final HTMLColor DEEPPINK1 = new HTMLColor("deeppink1", "#ff1493");
   public static final HTMLColor DEEPPINK2 = new HTMLColor("deeppink2", "#ee1289");
   public static final HTMLColor DEEPPINK3 = new HTMLColor("deeppink3", "#cd1076");
   public static final HTMLColor DEEPPINK4 = new HTMLColor("deeppink4", "#8b0a50");
   public static final HTMLColor DEEPSKYBLUE = new HTMLColor("deepskyblue", "#00bfff");
   public static final HTMLColor DEEPSKYBLUE1 = new HTMLColor("deepskyblue1", "#00bfff");
   public static final HTMLColor DEEPSKYBLUE2 = new HTMLColor("deepskyblue2", "#00b2ee");
   public static final HTMLColor DEEPSKYBLUE3 = new HTMLColor("deepskyblue3", "#009acd");
   public static final HTMLColor DEEPSKYBLUE4 = new HTMLColor("deepskyblue4", "#00688b");
   public static final HTMLColor DIMGRAY = new HTMLColor("dimgray", "#696969");
   public static final HTMLColor DIMGREY = new HTMLColor("dimgrey", "#696969");
   public static final HTMLColor DODGERBLUE = new HTMLColor("dodgerblue", "#1e90ff");
   public static final HTMLColor DODGERBLUE1 = new HTMLColor("dodgerblue1", "#1e90ff");
   public static final HTMLColor DODGERBLUE2 = new HTMLColor("dodgerblue2", "#1c86ee");
   public static final HTMLColor DODGERBLUE3 = new HTMLColor("dodgerblue3", "#1874cd");
   public static final HTMLColor DODGERBLUE4 = new HTMLColor("dodgerblue4", "#104e8b");
   public static final HTMLColor FIREBRICK = new HTMLColor("firebrick", "#b22222");
   public static final HTMLColor FIREBRICK1 = new HTMLColor("firebrick1", "#ff3030");
   public static final HTMLColor FIREBRICK2 = new HTMLColor("firebrick2", "#ee2c2c");
   public static final HTMLColor FIREBRICK3 = new HTMLColor("firebrick3", "#cd2626");
   public static final HTMLColor FIREBRICK4 = new HTMLColor("firebrick4", "#8b1a1a");
   public static final HTMLColor FLORALWHITE = new HTMLColor("floralwhite", "#fffaf0");
   public static final HTMLColor FORESTGREEN = new HTMLColor("forestgreen", "#228b22");
   public static final HTMLColor FUCHSIA = new HTMLColor("fuchsia", "#ff00ff");
   public static final HTMLColor GAINSBORO = new HTMLColor("gainsboro", "#dcdcdc");
   public static final HTMLColor GHOSTWHITE = new HTMLColor("ghostwhite", "#f8f8ff");
   public static final HTMLColor GOLD = new HTMLColor("gold", "#ffd700");
   public static final HTMLColor GOLD1 = new HTMLColor("gold1", "#ffd700");
   public static final HTMLColor GOLD2 = new HTMLColor("gold2", "#eec900");
   public static final HTMLColor GOLD3 = new HTMLColor("gold3", "#cdad00");
   public static final HTMLColor GOLD4 = new HTMLColor("gold4", "#8b7500");
   public static final HTMLColor GOLDENROD = new HTMLColor("goldenrod", "#daa520");
   public static final HTMLColor GOLDENROD1 = new HTMLColor("goldenrod1", "#ffc125");
   public static final HTMLColor GOLDENROD2 = new HTMLColor("goldenrod2", "#eeb422");
   public static final HTMLColor GOLDENROD3 = new HTMLColor("goldenrod3", "#cd9b1d");
   public static final HTMLColor GOLDENROD4 = new HTMLColor("goldenrod4", "#8b6914");
   public static final HTMLColor GRAY = new HTMLColor("gray", "#808080");
   public static final HTMLColor GRAY0 = new HTMLColor("gray0", "#000000");
   public static final HTMLColor GRAY1 = new HTMLColor("gray1", "#030303");
   public static final HTMLColor GRAY2 = new HTMLColor("gray2", "#050505");
   public static final HTMLColor GRAY3 = new HTMLColor("gray3", "#080808");
   public static final HTMLColor GRAY4 = new HTMLColor("gray4", "#0A0A0A");
   public static final HTMLColor GRAY5 = new HTMLColor("gray5", "#0D0D0D");
   public static final HTMLColor GRAY6 = new HTMLColor("gray6", "#0F0F0F");
   public static final HTMLColor GRAY7 = new HTMLColor("gray7", "#121212");
   public static final HTMLColor GRAY8 = new HTMLColor("gray8", "#141414");
   public static final HTMLColor GRAY9 = new HTMLColor("gray9", "#171717");
   public static final HTMLColor GRAY10 = new HTMLColor("gray10", "#1A1A1A");
   public static final HTMLColor GRAY11 = new HTMLColor("gray11", "#1C1C1C");
   public static final HTMLColor GRAY12 = new HTMLColor("gray12", "#1F1F1F");
   public static final HTMLColor GRAY13 = new HTMLColor("gray13", "#212121");
   public static final HTMLColor GRAY14 = new HTMLColor("gray14", "#242424");
   public static final HTMLColor GRAY15 = new HTMLColor("gray15", "#262626");
   public static final HTMLColor GRAY16 = new HTMLColor("gray16", "#292929");
   public static final HTMLColor GRAY17 = new HTMLColor("gray17", "#2B2B2B");
   public static final HTMLColor GRAY18 = new HTMLColor("gray18", "#2E2E2E");
   public static final HTMLColor GRAY19 = new HTMLColor("gray19", "#303030");
   public static final HTMLColor GRAY20 = new HTMLColor("gray20", "#333333");
   public static final HTMLColor GRAY21 = new HTMLColor("gray21", "#363636");
   public static final HTMLColor GRAY22 = new HTMLColor("gray22", "#383838");
   public static final HTMLColor GRAY23 = new HTMLColor("gray23", "#3B3B3B");
   public static final HTMLColor GRAY24 = new HTMLColor("gray24", "#3D3D3D");
   public static final HTMLColor GRAY25 = new HTMLColor("gray25", "#404040");
   public static final HTMLColor GRAY26 = new HTMLColor("gray26", "#424242");
   public static final HTMLColor GRAY27 = new HTMLColor("gray27", "#454545");
   public static final HTMLColor GRAY28 = new HTMLColor("gray28", "#474747");
   public static final HTMLColor GRAY29 = new HTMLColor("gray29", "#4A4A4A");
   public static final HTMLColor GRAY30 = new HTMLColor("gray30", "#4D4D4D");
   public static final HTMLColor GRAY31 = new HTMLColor("gray31", "#4F4F4F");
   public static final HTMLColor GRAY32 = new HTMLColor("gray32", "#525252");
   public static final HTMLColor GRAY33 = new HTMLColor("gray33", "#545454");
   public static final HTMLColor GRAY34 = new HTMLColor("gray34", "#575757");
   public static final HTMLColor GRAY35 = new HTMLColor("gray35", "#595959");
   public static final HTMLColor GRAY36 = new HTMLColor("gray36", "#5C5C5C");
   public static final HTMLColor GRAY37 = new HTMLColor("gray37", "#5E5E5E");
   public static final HTMLColor GRAY38 = new HTMLColor("gray38", "#616161");
   public static final HTMLColor GRAY39 = new HTMLColor("gray39", "#636363");
   public static final HTMLColor GRAY40 = new HTMLColor("gray40", "#666666");
   public static final HTMLColor GRAY41 = new HTMLColor("gray41", "#696969");
   public static final HTMLColor GRAY42 = new HTMLColor("gray42", "#6B6B6B");
   public static final HTMLColor GRAY43 = new HTMLColor("gray43", "#6E6E6E");
   public static final HTMLColor GRAY44 = new HTMLColor("gray44", "#707070");
   public static final HTMLColor GRAY45 = new HTMLColor("gray45", "#737373");
   public static final HTMLColor GRAY46 = new HTMLColor("gray46", "#757575");
   public static final HTMLColor GRAY47 = new HTMLColor("gray47", "#787878");
   public static final HTMLColor GRAY48 = new HTMLColor("gray48", "#7A7A7A");
   public static final HTMLColor GRAY49 = new HTMLColor("gray49", "#7D7D7D");
   public static final HTMLColor GRAY50 = new HTMLColor("gray50", "#7F7F7F");
   public static final HTMLColor GRAY51 = new HTMLColor("gray51", "#828282");
   public static final HTMLColor GRAY52 = new HTMLColor("gray52", "#858585");
   public static final HTMLColor GRAY53 = new HTMLColor("gray53", "#878787");
   public static final HTMLColor GRAY54 = new HTMLColor("gray54", "#8A8A8A");
   public static final HTMLColor GRAY55 = new HTMLColor("gray55", "#8C8C8C");
   public static final HTMLColor GRAY56 = new HTMLColor("gray56", "#8F8F8F");
   public static final HTMLColor GRAY57 = new HTMLColor("gray57", "#919191");
   public static final HTMLColor GRAY58 = new HTMLColor("gray58", "#949494");
   public static final HTMLColor GRAY59 = new HTMLColor("gray59", "#969696");
   public static final HTMLColor GRAY60 = new HTMLColor("gray60", "#999999");
   public static final HTMLColor GRAY61 = new HTMLColor("gray61", "#9C9C9C");
   public static final HTMLColor GRAY62 = new HTMLColor("gray62", "#9E9E9E");
   public static final HTMLColor GRAY63 = new HTMLColor("gray63", "#A1A1A1");
   public static final HTMLColor GRAY64 = new HTMLColor("gray64", "#A3A3A3");
   public static final HTMLColor GRAY65 = new HTMLColor("gray65", "#A6A6A6");
   public static final HTMLColor GRAY66 = new HTMLColor("gray66", "#A8A8A8");
   public static final HTMLColor GRAY67 = new HTMLColor("gray67", "#ABABAB");
   public static final HTMLColor GRAY68 = new HTMLColor("gray68", "#ADADAD");
   public static final HTMLColor GRAY69 = new HTMLColor("gray69", "#B0B0B0");
   public static final HTMLColor GRAY70 = new HTMLColor("gray70", "#B3B3B3");
   public static final HTMLColor GRAY71 = new HTMLColor("gray71", "#B5B5B5");
   public static final HTMLColor GRAY72 = new HTMLColor("gray72", "#B8B8B8");
   public static final HTMLColor GRAY73 = new HTMLColor("gray73", "#BABABA");
   public static final HTMLColor GRAY74 = new HTMLColor("gray74", "#BDBDBD");
   public static final HTMLColor GRAY75 = new HTMLColor("gray75", "#BFBFBF");
   public static final HTMLColor GRAY76 = new HTMLColor("gray76", "#C2C2C2");
   public static final HTMLColor GRAY77 = new HTMLColor("gray77", "#C4C4C4");
   public static final HTMLColor GRAY78 = new HTMLColor("gray78", "#C7C7C7");
   public static final HTMLColor GRAY79 = new HTMLColor("gray79", "#C9C9C9");
   public static final HTMLColor GRAY80 = new HTMLColor("gray80", "#CCCCCC");
   public static final HTMLColor GRAY81 = new HTMLColor("gray81", "#CFCFCF");
   public static final HTMLColor GRAY82 = new HTMLColor("gray82", "#D1D1D1");
   public static final HTMLColor GRAY83 = new HTMLColor("gray83", "#D4D4D4");
   public static final HTMLColor GRAY84 = new HTMLColor("gray84", "#D6D6D6");
   public static final HTMLColor GRAY85 = new HTMLColor("gray85", "#D9D9D9");
   public static final HTMLColor GRAY86 = new HTMLColor("gray86", "#DBDBDB");
   public static final HTMLColor GRAY87 = new HTMLColor("gray87", "#DEDEDE");
   public static final HTMLColor GRAY88 = new HTMLColor("gray88", "#E0E0E0");
   public static final HTMLColor GRAY89 = new HTMLColor("gray89", "#E3E3E3");
   public static final HTMLColor GRAY90 = new HTMLColor("gray90", "#E5E5E5");
   public static final HTMLColor GRAY91 = new HTMLColor("gray91", "#E8E8E8");
   public static final HTMLColor GRAY92 = new HTMLColor("gray92", "#EBEBEB");
   public static final HTMLColor GRAY93 = new HTMLColor("gray93", "#EDEDED");
   public static final HTMLColor GRAY94 = new HTMLColor("gray94", "#F0F0F0");
   public static final HTMLColor GRAY95 = new HTMLColor("gray95", "#F2F2F2");
   public static final HTMLColor GRAY96 = new HTMLColor("gray96", "#F5F5F5");
   public static final HTMLColor GRAY97 = new HTMLColor("gray97", "#F7F7F7");
   public static final HTMLColor GRAY98 = new HTMLColor("gray98", "#FAFAFA");
   public static final HTMLColor GRAY99 = new HTMLColor("gray99", "#FCFCFC");
   public static final HTMLColor GRAY100 = new HTMLColor("gray100", "#FFFFFF");
   public static final HTMLColor GREEN = new HTMLColor("green", "#008000");
   public static final HTMLColor GREEN1 = new HTMLColor("green1", "#00ff00");
   public static final HTMLColor GREEN2 = new HTMLColor("green2", "#00ee00");
   public static final HTMLColor GREEN3 = new HTMLColor("green3", "#00cd00");
   public static final HTMLColor GREEN4 = new HTMLColor("green4", "#008b00");
   public static final HTMLColor GREENYELLOW = new HTMLColor("greenyellow", "#adff2f");
   public static final HTMLColor GREY = new HTMLColor("grey", "#808080");
   public static final HTMLColor GREY0 = new HTMLColor("grey0", "#000000");
   public static final HTMLColor GREY1 = new HTMLColor("grey1", "#030303");
   public static final HTMLColor GREY2 = new HTMLColor("grey2", "#050505");
   public static final HTMLColor GREY3 = new HTMLColor("grey3", "#080808");
   public static final HTMLColor GREY4 = new HTMLColor("grey4", "#0A0A0A");
   public static final HTMLColor GREY5 = new HTMLColor("grey5", "#0D0D0D");
   public static final HTMLColor GREY6 = new HTMLColor("grey6", "#0F0F0F");
   public static final HTMLColor GREY7 = new HTMLColor("grey7", "#121212");
   public static final HTMLColor GREY8 = new HTMLColor("grey8", "#141414");
   public static final HTMLColor GREY9 = new HTMLColor("grey9", "#171717");
   public static final HTMLColor GREY10 = new HTMLColor("grey10", "#1A1A1A");
   public static final HTMLColor GREY11 = new HTMLColor("grey11", "#1C1C1C");
   public static final HTMLColor GREY12 = new HTMLColor("grey12", "#1F1F1F");
   public static final HTMLColor GREY13 = new HTMLColor("grey13", "#212121");
   public static final HTMLColor GREY14 = new HTMLColor("grey14", "#242424");
   public static final HTMLColor GREY15 = new HTMLColor("grey15", "#262626");
   public static final HTMLColor GREY16 = new HTMLColor("grey16", "#292929");
   public static final HTMLColor GREY17 = new HTMLColor("grey17", "#2B2B2B");
   public static final HTMLColor GREY18 = new HTMLColor("grey18", "#2E2E2E");
   public static final HTMLColor GREY19 = new HTMLColor("grey19", "#303030");
   public static final HTMLColor GREY20 = new HTMLColor("grey20", "#333333");
   public static final HTMLColor GREY21 = new HTMLColor("grey21", "#363636");
   public static final HTMLColor GREY22 = new HTMLColor("grey22", "#383838");
   public static final HTMLColor GREY23 = new HTMLColor("grey23", "#3B3B3B");
   public static final HTMLColor GREY24 = new HTMLColor("grey24", "#3D3D3D");
   public static final HTMLColor GREY25 = new HTMLColor("grey25", "#404040");
   public static final HTMLColor GREY26 = new HTMLColor("grey26", "#424242");
   public static final HTMLColor GREY27 = new HTMLColor("grey27", "#454545");
   public static final HTMLColor GREY28 = new HTMLColor("grey28", "#474747");
   public static final HTMLColor GREY29 = new HTMLColor("grey29", "#4A4A4A");
   public static final HTMLColor GREY30 = new HTMLColor("grey30", "#4D4D4D");
   public static final HTMLColor GREY31 = new HTMLColor("grey31", "#4F4F4F");
   public static final HTMLColor GREY32 = new HTMLColor("grey32", "#525252");
   public static final HTMLColor GREY33 = new HTMLColor("grey33", "#545454");
   public static final HTMLColor GREY34 = new HTMLColor("grey34", "#575757");
   public static final HTMLColor GREY35 = new HTMLColor("grey35", "#595959");
   public static final HTMLColor GREY36 = new HTMLColor("grey36", "#5C5C5C");
   public static final HTMLColor GREY37 = new HTMLColor("grey37", "#5E5E5E");
   public static final HTMLColor GREY38 = new HTMLColor("grey38", "#616161");
   public static final HTMLColor GREY39 = new HTMLColor("grey39", "#636363");
   public static final HTMLColor GREY40 = new HTMLColor("grey40", "#666666");
   public static final HTMLColor GREY41 = new HTMLColor("grey41", "#696969");
   public static final HTMLColor GREY42 = new HTMLColor("grey42", "#6B6B6B");
   public static final HTMLColor GREY43 = new HTMLColor("grey43", "#6E6E6E");
   public static final HTMLColor GREY44 = new HTMLColor("grey44", "#707070");
   public static final HTMLColor GREY45 = new HTMLColor("grey45", "#737373");
   public static final HTMLColor GREY46 = new HTMLColor("grey46", "#757575");
   public static final HTMLColor GREY47 = new HTMLColor("grey47", "#787878");
   public static final HTMLColor GREY48 = new HTMLColor("grey48", "#7A7A7A");
   public static final HTMLColor GREY49 = new HTMLColor("grey49", "#7D7D7D");
   public static final HTMLColor GREY50 = new HTMLColor("grey50", "#7F7F7F");
   public static final HTMLColor GREY51 = new HTMLColor("grey51", "#828282");
   public static final HTMLColor GREY52 = new HTMLColor("grey52", "#858585");
   public static final HTMLColor GREY53 = new HTMLColor("grey53", "#878787");
   public static final HTMLColor GREY54 = new HTMLColor("grey54", "#8A8A8A");
   public static final HTMLColor GREY55 = new HTMLColor("grey55", "#8C8C8C");
   public static final HTMLColor GREY56 = new HTMLColor("grey56", "#8F8F8F");
   public static final HTMLColor GREY57 = new HTMLColor("grey57", "#919191");
   public static final HTMLColor GREY58 = new HTMLColor("grey58", "#949494");
   public static final HTMLColor GREY59 = new HTMLColor("grey59", "#969696");
   public static final HTMLColor GREY60 = new HTMLColor("grey60", "#999999");
   public static final HTMLColor GREY61 = new HTMLColor("grey61", "#9C9C9C");
   public static final HTMLColor GREY62 = new HTMLColor("grey62", "#9E9E9E");
   public static final HTMLColor GREY63 = new HTMLColor("grey63", "#A1A1A1");
   public static final HTMLColor GREY64 = new HTMLColor("grey64", "#A3A3A3");
   public static final HTMLColor GREY65 = new HTMLColor("grey65", "#A6A6A6");
   public static final HTMLColor GREY66 = new HTMLColor("grey66", "#A8A8A8");
   public static final HTMLColor GREY67 = new HTMLColor("grey67", "#ABABAB");
   public static final HTMLColor GREY68 = new HTMLColor("grey68", "#ADADAD");
   public static final HTMLColor GREY69 = new HTMLColor("grey69", "#B0B0B0");
   public static final HTMLColor GREY70 = new HTMLColor("grey70", "#B3B3B3");
   public static final HTMLColor GREY71 = new HTMLColor("grey71", "#B5B5B5");
   public static final HTMLColor GREY72 = new HTMLColor("grey72", "#B8B8B8");
   public static final HTMLColor GREY73 = new HTMLColor("grey73", "#BABABA");
   public static final HTMLColor GREY74 = new HTMLColor("grey74", "#BDBDBD");
   public static final HTMLColor GREY75 = new HTMLColor("grey75", "#BFBFBF");
   public static final HTMLColor GREY76 = new HTMLColor("grey76", "#C2C2C2");
   public static final HTMLColor GREY77 = new HTMLColor("grey77", "#C4C4C4");
   public static final HTMLColor GREY78 = new HTMLColor("grey78", "#C7C7C7");
   public static final HTMLColor GREY79 = new HTMLColor("grey79", "#C9C9C9");
   public static final HTMLColor GREY80 = new HTMLColor("grey80", "#CCCCCC");
   public static final HTMLColor GREY81 = new HTMLColor("grey81", "#CFCFCF");
   public static final HTMLColor GREY82 = new HTMLColor("grey82", "#D1D1D1");
   public static final HTMLColor GREY83 = new HTMLColor("grey83", "#D4D4D4");
   public static final HTMLColor GREY84 = new HTMLColor("grey84", "#D6D6D6");
   public static final HTMLColor GREY85 = new HTMLColor("grey85", "#D9D9D9");
   public static final HTMLColor GREY86 = new HTMLColor("grey86", "#DBDBDB");
   public static final HTMLColor GREY87 = new HTMLColor("grey87", "#DEDEDE");
   public static final HTMLColor GREY88 = new HTMLColor("grey88", "#E0E0E0");
   public static final HTMLColor GREY89 = new HTMLColor("grey89", "#E3E3E3");
   public static final HTMLColor GREY90 = new HTMLColor("grey90", "#E5E5E5");
   public static final HTMLColor GREY91 = new HTMLColor("grey91", "#E8E8E8");
   public static final HTMLColor GREY92 = new HTMLColor("grey92", "#EBEBEB");
   public static final HTMLColor GREY93 = new HTMLColor("grey93", "#EDEDED");
   public static final HTMLColor GREY94 = new HTMLColor("grey94", "#F0F0F0");
   public static final HTMLColor GREY95 = new HTMLColor("grey95", "#F2F2F2");
   public static final HTMLColor GREY96 = new HTMLColor("grey96", "#F5F5F5");
   public static final HTMLColor GREY97 = new HTMLColor("grey97", "#F7F7F7");
   public static final HTMLColor GREY98 = new HTMLColor("grey98", "#FAFAFA");
   public static final HTMLColor GREY99 = new HTMLColor("grey99", "#FCFCFC");
   public static final HTMLColor GREY100 = new HTMLColor("grey100", "#FFFFFF");
   public static final HTMLColor HONEYDEW = new HTMLColor("honeydew", "#f0fff0");
   public static final HTMLColor HONEYDEW1 = new HTMLColor("honeydew1", "#f0fff0");
   public static final HTMLColor HONEYDEW2 = new HTMLColor("honeydew2", "#e0eee0");
   public static final HTMLColor HONEYDEW3 = new HTMLColor("honeydew3", "#c1cdc1");
   public static final HTMLColor HONEYDEW4 = new HTMLColor("honeydew4", "#838b83");
   public static final HTMLColor HOTPINK = new HTMLColor("hotpink", "#ff69b4");
   public static final HTMLColor HOTPINK1 = new HTMLColor("hotpink1", "#ff6eb4");
   public static final HTMLColor HOTPINK2 = new HTMLColor("hotpink2", "#ee6aa7");
   public static final HTMLColor HOTPINK3 = new HTMLColor("hotpink3", "#cd6090");
   public static final HTMLColor HOTPINK4 = new HTMLColor("hotpink4", "#8b3a62");
   public static final HTMLColor INDIANRED = new HTMLColor("indianred", "#cd5c5c");
   public static final HTMLColor INDIANRED1 = new HTMLColor("indianred1", "#ff6a6a");
   public static final HTMLColor INDIANRED2 = new HTMLColor("indianred2", "#ee6363");
   public static final HTMLColor INDIANRED3 = new HTMLColor("indianred3", "#cd5555");
   public static final HTMLColor INDIANRED4 = new HTMLColor("indianred4", "#8b3a3a");
   public static final HTMLColor IVORY = new HTMLColor("ivory", "#fffff0");
   public static final HTMLColor IVORY1 = new HTMLColor("ivory1", "#fffff0");
   public static final HTMLColor IVORY2 = new HTMLColor("ivory2", "#eeeee0");
   public static final HTMLColor IVORY3 = new HTMLColor("ivory3", "#cdcdc1");
   public static final HTMLColor IVORY4 = new HTMLColor("ivory4", "#8b8b83");
   public static final HTMLColor KHAKI1 = new HTMLColor("khaki1", "#fff68f");
   public static final HTMLColor KHAKI2 = new HTMLColor("khaki2", "#eee685");
   public static final HTMLColor KHAKI3 = new HTMLColor("khaki3", "#cdc673");
   public static final HTMLColor KHAKI4 = new HTMLColor("khaki4", "#8b864e");
   public static final HTMLColor LAVENDER = new HTMLColor("lavender", "#e6e6fa");
   public static final HTMLColor LAVENDERBLUSH = new HTMLColor("lavenderblush", "#fff0f5");
   public static final HTMLColor LAVENDERBLUSH1 = new HTMLColor("lavenderblush1", "#fff0f5");
   public static final HTMLColor LAVENDERBLUSH2 = new HTMLColor("lavenderblush2", "#eee0e5");
   public static final HTMLColor LAVENDERBLUSH3 = new HTMLColor("lavenderblush3", "#cdc1c5");
   public static final HTMLColor LAVENDERBLUSH4 = new HTMLColor("lavenderblush4", "#8b8386");
   public static final HTMLColor LAWNGREEN = new HTMLColor("lawngreen", "#7cfc00");
   public static final HTMLColor LEMONCHIFFON = new HTMLColor("lemonchiffon", "#fffacd");
   public static final HTMLColor LEMONCHIFFON1 = new HTMLColor("lemonchiffon1", "#fffacd");
   public static final HTMLColor LEMONCHIFFON2 = new HTMLColor("lemonchiffon2", "#eee9bf");
   public static final HTMLColor LEMONCHIFFON3 = new HTMLColor("lemonchiffon3", "#cdc9a5");
   public static final HTMLColor LEMONCHIFFON4 = new HTMLColor("lemonchiffon4", "#8b8970");
   public static final HTMLColor LIGHTBLUE = new HTMLColor("lightblue", "#add8e6");
   public static final HTMLColor LIGHTBLUE1 = new HTMLColor("lightblue1", "#bfefff");
   public static final HTMLColor LIGHTBLUE2 = new HTMLColor("lightblue2", "#b2dfee");
   public static final HTMLColor LIGHTBLUE3 = new HTMLColor("lightblue3", "#9ac0cd");
   public static final HTMLColor LIGHTBLUE4 = new HTMLColor("lightblue4", "#68838b");
   public static final HTMLColor LIGHTCORAL = new HTMLColor("lightcoral", "#f08080");
   public static final HTMLColor LIGHTCYAN = new HTMLColor("lightcyan", "#e0ffff");
   public static final HTMLColor LIGHTCYAN1 = new HTMLColor("lightcyan1", "#e0ffff");
   public static final HTMLColor LIGHTCYAN2 = new HTMLColor("lightcyan2", "#d1eeee");
   public static final HTMLColor LIGHTCYAN3 = new HTMLColor("lightcyan3", "#b4cdcd");
   public static final HTMLColor LIGHTCYAN4 = new HTMLColor("lightcyan4", "#7a8b8b");
   public static final HTMLColor LIGHTGOLDENROD = new HTMLColor("lightgoldenrod", "#eedd82");
   public static final HTMLColor LIGHTGOLDENROD1 = new HTMLColor("lightgoldenrod1", "#ffec8b");
   public static final HTMLColor LIGHTGOLDENROD2 = new HTMLColor("lightgoldenrod2", "#eedc82");
   public static final HTMLColor LIGHTGOLDENROD3 = new HTMLColor("lightgoldenrod3", "#cdbe70");
   public static final HTMLColor LIGHTGOLDENROD4 = new HTMLColor("lightgoldenrod4", "#8b814c");
   public static final HTMLColor LIGHTGOLDENRODYELLOW = new HTMLColor("lighttgoldenrodyellow", "#fafad2");
   public static final HTMLColor LIGHTGRAY = new HTMLColor("lightgray", "#d3d3d3");
   public static final HTMLColor LIGHTGREEN = new HTMLColor("lightgreen", "#90ee90");
   public static final HTMLColor LIGHTPINK = new HTMLColor("lightpink", "#ffb6c1");
   public static final HTMLColor LIGHTPINK1 = new HTMLColor("lightpink1", "#ffaeb9");
   public static final HTMLColor LIGHTPINK2 = new HTMLColor("lightpink2", "#eea2ad");
   public static final HTMLColor LIGHTPINK3 = new HTMLColor("lightpink3", "#cd8c95");
   public static final HTMLColor LIGHTPINK4 = new HTMLColor("lightpink4", "#8b5f65");
   public static final HTMLColor LIGHTSALMON = new HTMLColor("lightsalmon", "#ffa07a");
   public static final HTMLColor LIGHTSALMON1 = new HTMLColor("lightsalmon1", "#ffa07a");
   public static final HTMLColor LIGHTSALMON2 = new HTMLColor("lightsalmon2", "#ee9572");
   public static final HTMLColor LIGHTSALMON3 = new HTMLColor("lightsalmon3", "#cd8162");
   public static final HTMLColor LIGHTSALMON4 = new HTMLColor("lightsalmon4", "#8b5742");
   public static final HTMLColor LIGHTSEAGREEN = new HTMLColor("lightseagreen", "#20b2aa");
   public static final HTMLColor LIGHTSKYBLUE = new HTMLColor("lightskyblue", "#87cefa");
   public static final HTMLColor LIGHTSKYBLUE1 = new HTMLColor("lightskyblue1", "#b0e2ff");
   public static final HTMLColor LIGHTSKYBLUE2 = new HTMLColor("lightskyblue2", "#a4d3ee");
   public static final HTMLColor LIGHTSKYBLUE3 = new HTMLColor("lightskyblue3", "#8db6cd");
   public static final HTMLColor LIGHTSKYBLUE4 = new HTMLColor("lightskyblue4", "#607b8b");
   public static final HTMLColor LIGHTSLATEBLUE = new HTMLColor("lightslateblue", "#8470ff");
   public static final HTMLColor LIGHTSLATEGRAY = new HTMLColor("lightslategray", "#778899");
   public static final HTMLColor LIGHTSTEELBLUE = new HTMLColor("lightsteelblue", "#b0c4de");
   public static final HTMLColor LIGHTSTEELBLUE1 = new HTMLColor("lightsteelblue1", "#cae1ff");
   public static final HTMLColor LIGHTSTEELBLUE2 = new HTMLColor("lightsteelblue2", "#bcd2ee");
   public static final HTMLColor LIGHTSTEELBLUE3 = new HTMLColor("lightsteelblue3", "#a2b5cd");
   public static final HTMLColor LIGHTSTEELBLUE4 = new HTMLColor("lightsteelblue4", "#6e7b8b");
   public static final HTMLColor LIGHTYELLOW = new HTMLColor("lightyellow", "#ffffe0");
   public static final HTMLColor LIGHTYELLOW1 = new HTMLColor("lightyellow1", "#ffffe0");
   public static final HTMLColor LIGHTYELLOW2 = new HTMLColor("lightyellow2", "#eeeed1");
   public static final HTMLColor LIGHTYELLOW3 = new HTMLColor("lightyellow3", "#cdcdb4");
   public static final HTMLColor LIGHTYELLOW4 = new HTMLColor("lightyellow4", "#8b8b7a");
   public static final HTMLColor LIME = new HTMLColor("lime", "#00ff00");
   public static final HTMLColor LIMEGREEN = new HTMLColor("limegreen", "#32cd32");
   public static final HTMLColor LINEN = new HTMLColor("linen", "#faf0e6");
   public static final HTMLColor MAGENTA = new HTMLColor("magenta", "#ff00ff");
   public static final HTMLColor MAGENTA1 = new HTMLColor("magenta1", "#ff00ff");
   public static final HTMLColor MAGENTA2 = new HTMLColor("magenta2", "#ee00ee");
   public static final HTMLColor MAGENTA3 = new HTMLColor("magenta3", "#cd00cd");
   public static final HTMLColor MAGENTA4 = new HTMLColor("magenta4", "#8b008b");
   public static final HTMLColor MAROON = new HTMLColor("maroon", "#800000");
   public static final HTMLColor MAROON1 = new HTMLColor("maroon1", "#ff34b3");
   public static final HTMLColor MAROON2 = new HTMLColor("maroon2", "#ee30a7");
   public static final HTMLColor MAROON3 = new HTMLColor("maroon3", "#cd2990");
   public static final HTMLColor MAROON4 = new HTMLColor("maroon4", "#8b1c62");
   public static final HTMLColor MEDSPRINGGREEN = new HTMLColor("medspringgreen", "#00fa9a");
   public static final HTMLColor MEDIUMAQUAMARINE = new HTMLColor("mediumaquamarine", "#66cdaa");
   public static final HTMLColor MEDIUMBLUE = new HTMLColor("mediumblue", "#0000cd");
   public static final HTMLColor MEDIUMORCHID = new HTMLColor("mediumorchid", "#ba55d3");
   public static final HTMLColor MEDIUMORCHID1 = new HTMLColor("mediumorchid1", "#e066ff");
   public static final HTMLColor MEDIUMORCHID2 = new HTMLColor("mediumorchid2", "#d15fee");
   public static final HTMLColor MEDIUMORCHID3 = new HTMLColor("mediumorchid3", "#b452cd");
   public static final HTMLColor MEDIUMORCHID4 = new HTMLColor("mediumorchid4", "#7a378b");
   public static final HTMLColor MEDIUMPURPLE = new HTMLColor("mediumpurple", "#9370db");
   public static final HTMLColor MEDIUMPURPLE1 = new HTMLColor("mediumpurple1", "#ab82ff");
   public static final HTMLColor MEDIUMPURPLE2 = new HTMLColor("mediumpurple2", "#9f79ee");
   public static final HTMLColor MEDIUMPURPLE3 = new HTMLColor("mediumpurple3", "#8968cd");
   public static final HTMLColor MEDIUMPURPLE4 = new HTMLColor("mediumpurple4", "#5d478b");
   public static final HTMLColor MEDIUMSEAGREEN = new HTMLColor("mediumseagreen", "#3cb371");
   public static final HTMLColor MEDIUMSLATEBLUE = new HTMLColor("mediumslateblue", "#7b68ee");
   public static final HTMLColor MEDIUMTURQUOISE = new HTMLColor("mediumturquoise", "#48d1cc");
   public static final HTMLColor MEDIUMVIOLETRED = new HTMLColor("mediumvioletred", "#c71585");
   public static final HTMLColor MIDNIGHTBLUE = new HTMLColor("midnightblue", "#191970");
   public static final HTMLColor MINTCREAM = new HTMLColor("mintcream", "#f5fffa");
   public static final HTMLColor MISTYROSE = new HTMLColor("mistyrose", "#ffe4e1");
   public static final HTMLColor MISTYROSE1 = new HTMLColor("mistyrose1", "#ffe4e1");
   public static final HTMLColor MISTYROSE2 = new HTMLColor("mistyrose2", "#eed5d2");
   public static final HTMLColor MISTYROSE3 = new HTMLColor("mistyrose3", "#cdb7b5");
   public static final HTMLColor MISTYROSE4 = new HTMLColor("mistyrose4", "#8b7d7b");
   public static final HTMLColor MOCCASIN = new HTMLColor("moccasin", "#ffe4b5");
   public static final HTMLColor NAVAJOWHITE = new HTMLColor("navajowhite", "#ffdead");
   public static final HTMLColor NAVAJOWHITE1 = new HTMLColor("navajowhite1", "#ffdead");
   public static final HTMLColor NAVAJOWHITE2 = new HTMLColor("navajowhite2", "#eecfa1");
   public static final HTMLColor NAVAJOWHITE3 = new HTMLColor("navajowhite3", "#cdb38b");
   public static final HTMLColor NAVAJOWHITE4 = new HTMLColor("navajowhite4", "#8b795e");
   public static final HTMLColor NAVY = new HTMLColor("navy", "#000080");
   public static final HTMLColor NAVYBLUE = new HTMLColor("navyblue", "#000080");
   public static final HTMLColor OLDLACE = new HTMLColor("oldlace", "#fdf5e6");
   public static final HTMLColor OLIVE = new HTMLColor("olive", "#808000");
   public static final HTMLColor OLIVEDRAB = new HTMLColor("olivedrab", "#6b8e23");
   public static final HTMLColor OLIVEDRAB1 = new HTMLColor("olivedrab1", "#c0ff3e");
   public static final HTMLColor OLIVEDRAB2 = new HTMLColor("olivedrab2", "#b3ee3a");
   public static final HTMLColor OLIVEDRAB3 = new HTMLColor("olivedrab3", "#9acd32");
   public static final HTMLColor OLIVEDRAB4 = new HTMLColor("olivedrab4", "#698b22");
   public static final HTMLColor ORANGE = new HTMLColor("orange", "#ffa500");
   public static final HTMLColor ORANGE1 = new HTMLColor("orange1", "#ffa500");
   public static final HTMLColor ORANGE2 = new HTMLColor("orange2", "#ee9a00");
   public static final HTMLColor ORANGE3 = new HTMLColor("orange3", "#cd8500");
   public static final HTMLColor ORANGE4 = new HTMLColor("orange4", "#8b5a00");
   public static final HTMLColor ORANGERED = new HTMLColor("orangered", "#ff4500");
   public static final HTMLColor ORANGERED1 = new HTMLColor("orangered1", "#ff4500");
   public static final HTMLColor ORANGERED2 = new HTMLColor("orangered2", "#ee4000");
   public static final HTMLColor ORANGERED3 = new HTMLColor("orangered3", "#cd3700");
   public static final HTMLColor ORANGERED4 = new HTMLColor("orangered4", "#8b2500");
   public static final HTMLColor ORCHID = new HTMLColor("orchid", "#da70d6");
   public static final HTMLColor ORCHID1 = new HTMLColor("orchid1", "#ff83fa");
   public static final HTMLColor ORCHID2 = new HTMLColor("orchid2", "#ee7ae9");
   public static final HTMLColor ORCHID3 = new HTMLColor("orchid3", "#cd69c9");
   public static final HTMLColor ORCHID4 = new HTMLColor("orchid4", "#8b4789");
   public static final HTMLColor PALEGOLDENROD = new HTMLColor("palegoldenrod", "#eee8aa");
   public static final HTMLColor PALEGREEN = new HTMLColor("palegreen", "#98fb98");
   public static final HTMLColor PALEGREEN1 = new HTMLColor("palegreen1", "#9aff9a");
   public static final HTMLColor PALEGREEN2 = new HTMLColor("palegreen2", "#90ee90");
   public static final HTMLColor PALEGREEN3 = new HTMLColor("palegreen3", "#7ccd7c");
   public static final HTMLColor PALEGREEN4 = new HTMLColor("palegreen4", "#548b54");
   public static final HTMLColor PALETURQUOISE = new HTMLColor("paleturquoise", "#afeeee");
   public static final HTMLColor PALETURQUOISE1 = new HTMLColor("paleturquoise1", "#bbffff");
   public static final HTMLColor PALETURQUOISE2 = new HTMLColor("paleturquoise2", "#aeeeee");
   public static final HTMLColor PALETURQUOISE3 = new HTMLColor("paleturquoise3", "#96cdcd");
   public static final HTMLColor PALETURQUOISE4 = new HTMLColor("paleturquoise4", "#668b8b");
   public static final HTMLColor PALEVIOLETRED = new HTMLColor("palevioletred", "#db7093");
   public static final HTMLColor PALEVIOLETRED1 = new HTMLColor("palevioletred1", "#ff82ab");
   public static final HTMLColor PALEVIOLETRED2 = new HTMLColor("palevioletred2", "#ee799f");
   public static final HTMLColor PALEVIOLETRED3 = new HTMLColor("palevioletred3", "#cd6889");
   public static final HTMLColor PALEVIOLETRED4 = new HTMLColor("palevioletred4", "#8b475d");
   public static final HTMLColor PAPAYAWHIP = new HTMLColor("papayawhip", "#ffefd5");
   public static final HTMLColor PEACHPUFF = new HTMLColor("peachpuff", "#ffdab9");
   public static final HTMLColor PEACHPUFF1 = new HTMLColor("peachpuff1", "#ffdab9");
   public static final HTMLColor PEACHPUFF2 = new HTMLColor("peachpuff2", "#eecbad");
   public static final HTMLColor PEACHPUFF3 = new HTMLColor("peachpuff3", "#cdaf95");
   public static final HTMLColor PEACHPUFF4 = new HTMLColor("peachpuff4", "#8b7765");
   public static final HTMLColor PERU = new HTMLColor("peru", "#cd853f");
   public static final HTMLColor PINK = new HTMLColor("pink", "#ffc0cb");
   public static final HTMLColor PINK1 = new HTMLColor("pink1", "#ffb5c5");
   public static final HTMLColor PINK2 = new HTMLColor("pink2", "#eea9b8");
   public static final HTMLColor PINK3 = new HTMLColor("pink3", "#cd919e");
   public static final HTMLColor PINK4 = new HTMLColor("pink4", "#8b636c");
   public static final HTMLColor PLUM = new HTMLColor("plum", "#dda0dd");
   public static final HTMLColor PLUM1 = new HTMLColor("plum1", "#ffbbff");
   public static final HTMLColor PLUM2 = new HTMLColor("plum2", "#eeaeee");
   public static final HTMLColor PLUM3 = new HTMLColor("plum3", "#cd96cd");
   public static final HTMLColor PLUM4 = new HTMLColor("plum4", "#8b668b");
   public static final HTMLColor POWDERBLUE = new HTMLColor("powderblue", "#b0e0e6");
   public static final HTMLColor PURPLE = new HTMLColor("purple", "#800080");
   public static final HTMLColor PURPLE1 = new HTMLColor("purple1", "#9b30ff");
   public static final HTMLColor PURPLE2 = new HTMLColor("purple2", "#912cee");
   public static final HTMLColor PURPLE3 = new HTMLColor("purple3", "#7d26cd");
   public static final HTMLColor PURPLE4 = new HTMLColor("purple4", "#551a8b");
   public static final HTMLColor RED = new HTMLColor("red", "#ff0000");
   public static final HTMLColor RED1 = new HTMLColor("red1", "#ff0000");
   public static final HTMLColor RED2 = new HTMLColor("red2", "#ee0000");
   public static final HTMLColor RED3 = new HTMLColor("red3", "#cd0000");
   public static final HTMLColor RED4 = new HTMLColor("red4", "#8b0000");
   public static final HTMLColor ROSYBROWN = new HTMLColor("rosybrown", "#bc8f8f");
   public static final HTMLColor ROSYBROWN1 = new HTMLColor("rosybrown1", "#ffc1c1");
   public static final HTMLColor ROSYBROWN2 = new HTMLColor("rosybrown2", "#eeb4b4");
   public static final HTMLColor ROSYBROWN3 = new HTMLColor("rosybrown3", "#cd9b9b");
   public static final HTMLColor ROSYBROWN4 = new HTMLColor("rosybrown4", "#8b6969");
   public static final HTMLColor ROYALBLUE = new HTMLColor("royalblue", "#4169e1");
   public static final HTMLColor ROYALBLUE1 = new HTMLColor("royalblue1", "#4876ff");
   public static final HTMLColor ROYALBLUE2 = new HTMLColor("royalblue2", "#436eee");
   public static final HTMLColor ROYALBLUE3 = new HTMLColor("royalblue3", "#3a5fcd");
   public static final HTMLColor ROYALBLUE4 = new HTMLColor("royalblue4", "#27408b");
   public static final HTMLColor SADDLEBROWN = new HTMLColor("saddlebrown", "#8b4513");
   public static final HTMLColor SALMON = new HTMLColor("salmon", "#fa8072");
   public static final HTMLColor SALMON1 = new HTMLColor("salmon1", "#ff8c69");
   public static final HTMLColor SALMON2 = new HTMLColor("salmon2", "#ee8262");
   public static final HTMLColor SALMON3 = new HTMLColor("salmon3", "#cd7054");
   public static final HTMLColor SALMON4 = new HTMLColor("salmon4", "#8b4c39");
   public static final HTMLColor SANDYBROWN = new HTMLColor("sandybrown", "#f4a460");
   public static final HTMLColor SEAGREEN = new HTMLColor("seagreen", "#2e8b57");
   public static final HTMLColor SEAGREEN1 = new HTMLColor("seagreen1", "#54ff9f");
   public static final HTMLColor SEAGREEN2 = new HTMLColor("seagreen2", "#4eee94");
   public static final HTMLColor SEAGREEN3 = new HTMLColor("seagreen3", "#43cd80");
   public static final HTMLColor SEAGREEN4 = new HTMLColor("seagreen4", "#2e8b57");
   public static final HTMLColor SEASHELL = new HTMLColor("seashell", "#fff5ee");
   public static final HTMLColor SEASHELL1 = new HTMLColor("seashell1", "#fff5ee");
   public static final HTMLColor SEASHELL2 = new HTMLColor("seashell2", "#eee5de");
   public static final HTMLColor SEASHELL3 = new HTMLColor("seashell3", "#cdc5bf");
   public static final HTMLColor SEASHELL4 = new HTMLColor("seashell4", "#8b8682");
   public static final HTMLColor SIENNA = new HTMLColor("sienna", "#a0522d");
   public static final HTMLColor SIENNA1 = new HTMLColor("sienna1", "#ff8247");
   public static final HTMLColor SIENNA2 = new HTMLColor("sienna2", "#ee7942");
   public static final HTMLColor SIENNA3 = new HTMLColor("sienna3", "#cd6839");
   public static final HTMLColor SIENNA4 = new HTMLColor("sienna4", "#8b4726");
   public static final HTMLColor SILVER = new HTMLColor("silver", "#c0c0c0");
   public static final HTMLColor SKYBLUE = new HTMLColor("skyblue", "#87ceeb");
   public static final HTMLColor SKYBLUE1 = new HTMLColor("skyblue1", "#87ceff");
   public static final HTMLColor SKYBLUE2 = new HTMLColor("skyblue2", "#7ec0ee");
   public static final HTMLColor SKYBLUE3 = new HTMLColor("skyblue3", "#6ca6cd");
   public static final HTMLColor SKYBLUE4 = new HTMLColor("skyblue4", "#4a708b");
   public static final HTMLColor SLATEBLUE = new HTMLColor("slateblue", "#6a5acd");
   public static final HTMLColor SLATEBLUE1 = new HTMLColor("slateblue1", "#836fff");
   public static final HTMLColor SLATEBLUE2 = new HTMLColor("slateblue2", "#7a67ee");
   public static final HTMLColor SLATEBLUE3 = new HTMLColor("slateblue3", "#6959cd");
   public static final HTMLColor SLATEBLUE4 = new HTMLColor("slateblue4", "#473c8b");
   public static final HTMLColor SLATEGRAY = new HTMLColor("slategray", "#708090");
   public static final HTMLColor SLATEGRAY1 = new HTMLColor("slategray1", "#c6e2ff");
   public static final HTMLColor SLATEGRAY2 = new HTMLColor("slategray2", "#b9d3ee");
   public static final HTMLColor SLATEGRAY3 = new HTMLColor("slategray3", "#9fb6cd");
   public static final HTMLColor SLATEGRAY4 = new HTMLColor("slategray4", "#6c7b8b");
   public static final HTMLColor SLATEGREY = new HTMLColor("slategrey", "#708090");
   public static final HTMLColor SLATEGREY1 = new HTMLColor("slategrey1", "#c6e2ff");
   public static final HTMLColor SLATEGREY2 = new HTMLColor("slategrey2", "#b9d3ee");
   public static final HTMLColor SLATEGREY3 = new HTMLColor("slategrey3", "#9fb6cd");
   public static final HTMLColor SLATEGREY4 = new HTMLColor("slategrey4", "#6c7b8b");
   public static final HTMLColor SNOW = new HTMLColor("snow", "#fffafa");
   public static final HTMLColor SNOW1 = new HTMLColor("snow1", "#fffafa");
   public static final HTMLColor SNOW2 = new HTMLColor("snow2", "#eee9e9");
   public static final HTMLColor SNOW3 = new HTMLColor("snow3", "#cdc9c9");
   public static final HTMLColor SNOW4 = new HTMLColor("snow4", "#8b8989");
   public static final HTMLColor SPRINGGREEN = new HTMLColor("springgreen", "#00ff7f");
   public static final HTMLColor SPRINGGREEN1 = new HTMLColor("springgreen1", "#00ff7f");
   public static final HTMLColor SPRINGGREEN2 = new HTMLColor("springgreen2", "#00ee76");
   public static final HTMLColor SPRINGGREEN3 = new HTMLColor("springgreen3", "#00cd66");
   public static final HTMLColor SPRINGGREEN4 = new HTMLColor("springgreen4", "#008b45");
   public static final HTMLColor STEELBLUE = new HTMLColor("steelblue", "#4682b4");
   public static final HTMLColor STEELBLUE1 = new HTMLColor("steelblue1", "#63b8ff");
   public static final HTMLColor STEELBLUE2 = new HTMLColor("steelblue2", "#5cacee");
   public static final HTMLColor STEELBLUE3 = new HTMLColor("steelblue3", "#4f94cd");
   public static final HTMLColor STEELBLUE4 = new HTMLColor("steelblue4", "#36648b");
   public static final HTMLColor TAN = new HTMLColor("tan", "#d2b48c");
   public static final HTMLColor TAN1 = new HTMLColor("tan1", "#ffa54f");
   public static final HTMLColor TAN2 = new HTMLColor("tan2", "#ee9a49");
   public static final HTMLColor TAN3 = new HTMLColor("tan3", "#cd853f");
   public static final HTMLColor TAN4 = new HTMLColor("tan4", "#8b5a2b");
   public static final HTMLColor TEAL = new HTMLColor("teal", "#008080");
   public static final HTMLColor THISTLE = new HTMLColor("thistle", "#d8bfd8");
   public static final HTMLColor THISTLE1 = new HTMLColor("thistle1", "#ffe1ff");
   public static final HTMLColor THISTLE2 = new HTMLColor("thistle2", "#eed2ee");
   public static final HTMLColor THISTLE3 = new HTMLColor("thistle3", "#cdb5cd");
   public static final HTMLColor THISTLE4 = new HTMLColor("thistle4", "#8b7b8b");
   public static final HTMLColor TOMATO = new HTMLColor("tomato", "#ff6347");
   public static final HTMLColor TOMATO1 = new HTMLColor("tomato1", "#ff6347");
   public static final HTMLColor TOMATO2 = new HTMLColor("tomato2", "#ee5c42");
   public static final HTMLColor TOMATO3 = new HTMLColor("tomato3", "#cd4f39");
   public static final HTMLColor TOMATO4 = new HTMLColor("tomato4", "#8b3626");
   public static final HTMLColor TURQUOISE = new HTMLColor("turquoise", "#40e0d0");
   public static final HTMLColor TURQUOISE1 = new HTMLColor("turquoise1", "#00f5ff");
   public static final HTMLColor TURQUOISE2 = new HTMLColor("turquoise2", "#00e5ee");
   public static final HTMLColor TURQUOISE3 = new HTMLColor("turquoise3", "#00c5cd");
   public static final HTMLColor TURQUOISE4 = new HTMLColor("turquoise4", "#00868b");
   public static final HTMLColor VIOLET = new HTMLColor("violet", "#ee82ee");
   public static final HTMLColor VIOLETRED = new HTMLColor("violetred", "#d02090");
   public static final HTMLColor VIOLETRED1 = new HTMLColor("violetred1", "#ff3e96");
   public static final HTMLColor VIOLETRED2 = new HTMLColor("violetred2", "#ee3a8c");
   public static final HTMLColor VIOLETRED3 = new HTMLColor("violetred3", "#cd3278");
   public static final HTMLColor VIOLETRED4 = new HTMLColor("violetred4", "#8b2252");
   public static final HTMLColor WHEAT = new HTMLColor("wheat", "#f5deb3");
   public static final HTMLColor WHEAT1 = new HTMLColor("wheat1", "#ffe7ba");
   public static final HTMLColor WHEAT2 = new HTMLColor("wheat2", "#eed8ae");
   public static final HTMLColor WHEAT3 = new HTMLColor("wheat3", "#cdba96");
   public static final HTMLColor WHEAT4 = new HTMLColor("wheat4", "#8b7e66");
   public static final HTMLColor WHITE = new HTMLColor("white", "#ffffff");
   public static final HTMLColor WHITESMOKE = new HTMLColor("whitesmoke", "#f5f5f5");
   public static final HTMLColor YELLOW = new HTMLColor("yellow", "#ffff00");
   public static final HTMLColor YELLOW1 = new HTMLColor("yellow1", "#ffff00");
   public static final HTMLColor YELLOW2 = new HTMLColor("yellow2", "#eeee00");
   public static final HTMLColor YELLOW3 = new HTMLColor("yellow3", "#cdcd00");
   public static final HTMLColor YELLOW4 = new HTMLColor("yellow4", "#8b8b00");
   public static final HTMLColor YELLOWGREEN = new HTMLColor("yellowgreen", "#9acd32");
   protected String name;
   protected String hexRGB;

   protected HTMLColor(String name, String hexRGB) {
      super(getRed(hexRGB), getGreen(hexRGB), getBlue(hexRGB));
      this.name = name.toLowerCase();
      this.hexRGB = hexRGB.toLowerCase();
      nameToColorMap.put(name, this);
      nameToColorMap.put(hexRGB, this);
   }

   public String getHexRGB() {
      return this.hexRGB;
   }

   public String getName() {
      return this.name;
   }

   public static int getRed(String hexRGB) {
      if (hexRGB.length() == 7 && hexRGB.charAt(0) == '#') {
         return Integer.parseInt(hexRGB.substring(1, 3), 16);
      } else {
         throw new IllegalArgumentException("Invalid hexadecimal RGB string format: " + hexRGB);
      }
   }

   public static int getGreen(String hexRGB) {
      if (hexRGB.length() == 7 && hexRGB.charAt(0) == '#') {
         return Integer.parseInt(hexRGB.substring(3, 5), 16);
      } else {
         throw new IllegalArgumentException("Invalid hexadecimal RGB string format: " + hexRGB);
      }
   }

   public static int getBlue(String hexRGB) {
      if (hexRGB.length() == 7 && hexRGB.charAt(0) == '#') {
         return Integer.parseInt(hexRGB.substring(5), 16);
      } else {
         throw new IllegalArgumentException("Invalid hexadecimal RGB string format: " + hexRGB);
      }
   }

   public String toHTML() {
      return toHTML(this);
   }

   public static String toHTML(Color color) {
      if (color instanceof HTMLColor) {
         return ((HTMLColor)color).getHexRGB();
      } else {
         String html = (String)colorToStringMap.get(color);
         if (html == null) {
            StringBuffer buffer = new StringBuffer(7);
            buffer.append('#');
            ByteUtils.appendHexString((byte)color.getRed(), buffer);
            ByteUtils.appendHexString((byte)color.getGreen(), buffer);
            ByteUtils.appendHexString((byte)color.getBlue(), buffer);
            html = buffer.toString();
            colorToStringMap.put(color, html);
         }

         return html;
      }
   }

   public static Color valueOf(String htmlColor) {
      Color color = (Color)nameToColorMap.get(htmlColor.toLowerCase());
      if (color == null && htmlColor.startsWith("#") && htmlColor.length() == 7) {
         color = new Color(getRed(htmlColor), getGreen(htmlColor), getBlue(htmlColor));
         nameToColorMap.put(htmlColor, color);
      }

      return color;
   }
}
